### ISSUE TITLE
amzn/web-app-starter-kit-for-fire-tv

### ISSUE THREAD

**Issue by panatapattu** [amzn/web-app-starter-kit-for-fire-tv#16]
I need to use "simple-live" in Fire TV app. But it is not working and throwing an error. Here is the link I checked.
http://amzn.github.io/web-app-starter-kit-for-fire-tv/simple-live/

**Comment by craigcbrunner-amazon** [comment]
Hey,
Are you testing on a desktop browser? The live stream is an HLS video stream(m3u8), most desktop browsers do not support this format in their HTML5 players, so the player throws an unsupported error on desktop, which in turn goes through our error handling and shows that pop up. However the FireTV device does support HLS streaming in the HTML5 player, and should not throw this error. If you use the Web App Tester on the device with that URL the stream should play correctly.
Let me know if you have any other questions.
Thanks,
Craig

**Comment by panatapattu** [comment]
Hi,
Thank you. Yes it is working when I check with the device.

I am having a simple question. Can I use my own custom CSS with firetv css. Because I changed firetv.css.

Now, when I play Live and when I trying to back, it is showing black screen. For other videos (not  live) it is working fine.

**Comment by panatapattu** [comment]
It is working fine.
Thanks

**Comment by craigcbrunner-amazon** [comment]
Marking as closed, thanks!
