### ISSUE TITLE
In live Player, Player Control Container not showing when it is loading.

### ISSUE THREAD

**Issue by panatapattu** [amzn/web-app-starter-kit-for-fire-tv#17]
Hi,
In live, Player Control Container not showing when it is loading. For other videos except Live Streaming working fine.

But when I press up key in Live Streaming, it is showing the Controllers and hiding. I need to show the Controls when it is loading like other videos.

How can I fix this..?

**Comment by craigcbrunner-amazon** [comment]
This is actually a webview issue, HLS videos sometimes do not show DOM elements that are overlaid on top of them in the loading stages of the video, we are aware of this bug the webview team is looking at a fix. If they fix it it will be included in an OTA release on FireTV and the controls will just start working, until then we don't have a fix for this.

**Comment by maryga-amazon** [comment]
This issue has been fixed in the web engine.
