### ISSUE TITLE
Touch controls are broken

### ISSUE THREAD

**Issue by paulwhiting** [amzn/web-app-starter-kit-for-fire-tv#18]
The subcategory example and probably others doesn't work in touch enabled browsers so I can't release my web app for devices other than the firetv. Navigation in general doesn't work.

**Comment by craigcbrunner-amazon** [comment]
This is a valid issue, subcategories don't work with touch controls, we will add it to our bug list.

**Comment by maryga-amazon** [comment]
This template is currently only supporting Fire TV devices.
