### ISSUE TITLE
Not able to buy on fire stick

### ISSUE THREAD

**Issue by renancarvalho** [amzn/web-app-starter-kit-for-fire-tv#28]
When I run the example (https://amzn.github.io/web-app-starter-kit-for-fire-tv/iap-entitlements/) in browser it works good. But when I try to load the Url(using https) using the web app tester on fire stick, The app loads but I cannot buy.
I got this error from browser console.

![screen shot 2016-01-15 at 20 39 46](https://cloud.githubusercontent.com/assets/2653810/12363280/3a3a2398-bbc8-11e5-948e-f8c3ecfb1b87.png)

any clue ?

Thanks

**Comment by maryga-amazon** [comment]
In order to use IAP, the page must be fully secured with https (please see 'Set Up' in the _In App Purchasing_ document)
