### ISSUE TITLE
DIAL support

### ISSUE THREAD

**Issue by luke** [amzn/web-app-starter-kit-for-fire-tv#3]
Hi, 

I'm rather confused about how to go about testing DIAL with a web app on Fire TV. I've found docs on how to launch android apps using DIAL (1) but nothing that explains how to do the same thing with web apps. It would seem logical to support DIAL for web apps too. Is it possible and if so how would I go about testing it? 

1: https://developer.amazon.com/public/solutions/devices/fire-tv/docs/dial-integration

- Luke

**Comment by russellbeattie-amazon** [comment]
Hi Luke!

This project only focuses on the HTML5 layer of a media app. DIAL inherently uses native integration, as it's a system to wire up network events to Android Intents. You could enable this functionality by using a hybrid app approach using Cordova, for example, and adding in the custom JavaScript handlers that would respond to a DIAL intent message, but this isn't handled automatically by the web engine. I'll pass along the idea as you're right - it definitely seems like something that web apps should do out of the box.

Thanks,

-Russ

**Comment by craigcbrunner-amazon** [comment]
Hey Luke,
Did this answer your question? I will close the issue if so.
Thanks!
-Craig

**Comment by craigcbrunner-amazon** [comment]
Going to close this issue as resolved. Thanks!
