### ISSUE TITLE
Stream Hangs on Amazon Fire TV and Fire TV Stick

### ISSUE THREAD

**Issue by rwatts9942** [amzn/web-app-starter-kit-for-fire-tv#33]
I am streaming HLS and am running into an issue where:

1) On the Fire TV - It hangs at points, for several seconds, and the resumes.  It doesn't appear to be a buffering issue as the buffering graphic doesn't appear.  It just freezes for several seconds.
2) On the Fire TV Stick - It just hangs and just doesn't seem to recover.

I have a Fire TV but don't have a Fire TV Stick to test with and I suspect that the issue is the same issue.  The stick is basically the same as the Fire TV but with less resources.  I am getting feedback on the stick from other people and it is possible that they just aren't waiting long enough.

Here is what I am able to log on my Fire TV...

This always occurs right when the hang happens:
I/AudioFlinger(  178): BUFFER TIMEOUT: remove(4098) from active list on thread 0xf553d008
D/AudioFlinger(  178): Disable DS for device=0x400profile=0x1
W/CustomAudioPolicyManager(  178): getDeviceForStrategy() unknown strategy: 6
W/CustomAudioPolicyManager(  178): getDeviceForStrategy() unknown strategy: 7
W/CustomAudioPolicyManager(  178): getDeviceForStrategy() unknown strategy: 8

This is consistently logged during the stream when playback is working:
E/MFV_COMMON(  178): [Warning] profile: 77, level: 41, bDirect8x8InferenceFlag should be 1 (0)
E/MFV_COMMON(  178): u4LevelIdc 41
E/MFV_COMMON(  178): handleSPSNALU() 1 u4LevelIdc 41
E/MFV_COMMON(  178): vdec_drv_h264_decode, u4LevelIdc 41
E/MFV_COMMON(  178): getDpbSize u4NumRefFrames (3), u4DpbSize (9)!!
E/MFV_COMMON(  178): [Debug] getDpbSize final u4DpbSize (9)!!
E/MFV_COMMON(  178): handleSPSNALU() 2 u4LevelIdc 41
W/MFV_COMMON(  178): [Warning] Multi NAL case 1, 30
W/MFV_COMMON(  178): [Warning] Multi NAL case 2
E/MFV_COMMON(  178): u4LevelIdc 41

Any ideas on how to resolve this?

I am streaming from Wowza servers and using Akamai as a CDN.  The streams work fine the web and other CTV devices (e.g. Roku).

**Comment by rdosser** [comment]
@rwatts9942 What did you find? I'm seeing freezes after two instances of "unknown strategy: 6" and then it unfreezes after two more.
