### ISSUE TITLE
Sample Does Not Work

### ISSUE THREAD

**Issue by bcolflesh** [amzn/web-app-starter-kit-for-fire-tv#35]
Using the unaltered current sample and the sideload to device + WAT equals:

"Video Playback Error" An unexpected error occurred. Select OK to exit.

Does anyone have a working version for the latest API at Brightcove?

**Comment by bcolflesh** [comment]
Note this is in reference to the Brightcove specific project outlined here:

https://github.com/amzn/web-app-starter-kit-for-fire-tv/blob/master/docs/brightcove.md

**Comment by CrandellWS** [comment]
Believe you might need to setup the config part and not just run it...

Look into 

https://github.com/amzn/web-app-starter-kit-for-fire-tv/blob/master/src/projects/brightcove/init.js

**Comment by bcolflesh** [comment]
You'd be wrong - if you read the file, they have sample account data that should work. Of course, I tried my real account as well - same problem.

**Comment by CrandellWS** [comment]
in anycase the README.md clearly states what I quoted previously:

**To build your own Brightcove app**
# **you need to modify the init.js file.**

cheers

**Comment by bcolflesh** [comment]
LOL, you're a piece of work! For folks who refuse to read or understand documentation files, this one says:

"NOTE: the sample project uses our Brightcove Test account that has sample content"

and then has instructions to zip and play this on your FireTV to demonstrate the working design with existing Brightcove assets for your evaluation. Then at the bottom, encourages you to change the init file to match your own information.

But it doesn't work.

**Comment by CrandellWS** [comment]
Truth is I posted that and tried to delete it but was to late before I realize you are right... it does say it would work... and I got it to work (with some issues)

Firstly I am using Ubuntu 16.04 and following the instructions to install the **npm package serve** is poin tless as it does not work out the box... So I have decided to use a personally more prefered package that just works out the box:
> https://www.npmjs.com/package/http-server

    npm install http-server -g

Also I seem to have had some CORS trouble:
> https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

So after installing everything and using Gulp:

    gulp build

And using the http-serve package in the produced out folder the fisrt screen is an error like:
![screenshot from 2016-12-20 14-10-52](https://cloud.githubusercontent.com/assets/5300522/21364285/30309a56-c6be-11e6-8c25-454818381593.png)

SO I intalled the chrome extension 
> https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi?utm_source=chrome-app-launcher-info-dialog
### Allow-Control-Allow-Origin: *

Once enabled it all worked ... see the green icon by the broswer address bar that was red before...

![screenshot from 2016-12-20 14-15-36](https://cloud.githubusercontent.com/assets/5300522/21364441/e5579dee-c6be-11e6-94e5-cce05cf2d7e7.png)


## Enabling CORS will break other sites like GitHub.... beaware ...
Might be better to run a seperate Chrome profile just for the seperation of the testing....

**Comment by bcolflesh** [comment]
That's cool and I didn't get a chance to try it in a browser at all - but as stated in the OP, I'm testing directly on a FireTV device. I've done a couple set-top device projects now and browser testing is useless for the most part other than protoyping. I'd like Brightcove to update this for their current API so the sample project works as advertised on the device as advertised.

**Comment by maryga-amazon** [comment]
In order to get this working on Fire TV (for testing in WAT & submitting to appstore). Brightcove apps must be packaged apps (zip file instead of URL). This is because the packaged app includes the web app components and it is served from the local filesystem, this will solve the CORS issues.
