### ISSUE TITLE
Unable to play live HLS video

### ISSUE THREAD

**Issue by sgloutnikov** [amzn/web-app-starter-kit-for-fire-tv#38]
I am unable to play any live HLS video, even using the very basic demo application. Playing the live video gives me an instant `Video Playback Error`. 

Here is the output from the console:

ErrorType : Video Playback Error
ErrorMessage : Video source not available or supported
ErrorStack : Error
    at ErrorHandler.genStack (http://localhost:3000/js/error-handler.js:172:21)
    at PlayerView.<anonymous> (http://localhost:3000/js/player-view.js:173:57)

I am using the sample `simple-live` and have only changed the videoUrl to a working URL inside the genericLiveData JSON.

{
            "id": "live-id-1",
            "title": "NASA Live Stream",
            "thumbURL": "assets/l11.jpg",
            "imgURL": "assets/nasa-logo.jpg",
            "videoURL": "https://nasa-i.akamaihd.net/hls/live/253566/NTV-Media/master.m3u8",
            "type": "video-live",
            "alwaysLive": true, 
            "description": "The NASA Live Public TV Channel."
}

**Comment by russellbeattie** [comment]
Are you using Chrome Desktop? It doesn't support HLS. Try another browser.

**Comment by sgloutnikov** [comment]
Thanks, that was it! Works on Safari in MacOS.
