### ISSUE TITLE
Channel Login?

### ISSUE THREAD

**Issue by cssagogo** [amzn/web-app-starter-kit-for-fire-tv#43]
Any known examples of web app channels with customer login?  Is anyone at Amazon still maintaining this project?

**Comment by SarcasmAppreciated** [comment]
Sorry, customer login? As in Amazon login?

**Comment by maryga-amazon** [comment]
Can you specify what type of login you are looking for? Or are you asking if any apps using this project require authentication of any kind?

**Comment by maryga-amazon** [comment]
There is currently no module for handling login. Web apps will support authentication, but it will need to be built in. Minimally you would need a method for validating/confirming valid user session, a UI component, and API integration for the authentication.
