### ISSUE TITLE
Where does app.data.appLogo get set?

### ISSUE THREAD

**Issue by cssagogo** [amzn/web-app-starter-kit-for-fire-tv#44]
Inside app.js, I see the following code...

```
            if (app.data.appLogo) {
                logo = app.data.appLogo;
            } 
            else {
                logo = "assets/img_logo.png";
            }
```
Where is appLogo suppose to be set?  I don't see any references to it being added to app.data.

**Comment by russellbeattie-amazon** [comment]
The appLogo value is an optional URL that can be be set in the data Model - which ever one is being used. If you want to wire it up, you could add 

appLogo:"./assets/mylogo.png" 

to settings variable in the project's init.js , and then modify the model (model-json.js, model-mrss.js, etc.) to include that logo in the constructor:

this.appLogo = appSettings.appLogo;

The app will then pick up that logo.

Hope that helps.
