### ISSUE TITLE
Problems with multiPlaylists channel?

### ISSUE THREAD

**Issue by perrycbrown** [amzn/web-app-starter-kit-for-fire-tv#45]
multiPlaylists channel in /out/youtube/js/init.js is still not working for me. Here is snippet (actual ids replaced):

        channels: [
            {
                type: "playlist",
                id: "XXXXXXXXXXXXX",
                title: "Daily Broadcast Audio"
            },
            {
                type: "playlist",
                id: "XXXXXXXXXXXXX",
                title: "Recent Video Sermons"
            },
            {
                type: "multiPlaylists",
                ids: ["XXXXXXXXXXXXX",
                      "XXXXXXXXXXXXX",
                      "XXXXXXXXXXXXX"],
                title: "Video Series Archive"
            },
        ],

And all I'm seeing is the attached, only Daily Broadcast Audio and Recent Video Sermons in drop down nav menu.

I've also tried using ONLY the multiPlaylists channel (deleted the other channels there) and that also does not work.

Suggestions?

![screen shot 2018-01-31 at 1 54 47 pm](https://user-images.githubusercontent.com/3799732/35644565-dedf53f6-068e-11e8-9498-38dab6957de2.png)

**Comment by perrycbrown** [comment]
Really need an answer to this. Anybody monitoring the issues for this repository?

**Comment by krossa-lab126** [comment]
Hi Perry. I'll look into this issue today and get back to you ASAP.

**Comment by perrycbrown** [comment]
Thanks!

**Comment by maryga-amazon** [comment]
Hi Perry,

It should be an easy fix to get this working. Please do the following in your pre-built project folder:

**1. Update the model-youtube-api.js:**
Add the following to the loadPremadeChannels method as an additional if/else block :

```
 else if (this.premadeChannels[i].type === "multiPlaylists") {
                    this.channelData.push({
                        type: "multiPlaylists",
                        ids: this.premadeChannels[i].ids
                    });
                    this.categoryData.push(this.premadeChannels[i].title);
                }
```

**2.Update your project's build.json file to include the subcat-view in the appJS section:**

`        "../../common/js/subcat-view.js",`

**3. Rebuild your app and you should be good to go.**

**Comment by perrycbrown** [comment]
Wonderful! Thanks!

Would love to keep the drop-down category menu in upper left on the series playlist screen, like the attached. That possible?

![screen shot 2018-02-01 at 2 25 35 pm](https://user-images.githubusercontent.com/3799732/35701611-206751b6-075c-11e8-971f-41b4e1a46934.png)

**Comment by maryga-amazon** [comment]
Hi Perry,

Currently, there is no setting for this. It would require functionality changes in the app.

**Comment by perrycbrown** [comment]
Understood :-) Thanks again!

**Comment by yanniboi** [comment]
Why has this issue been closed? The documentation advertises a feature that does not work unless you hack the model. Should this not either get fixed, or the documentation be updates?
