### ISSUE TITLE
Can the dataURL in init.js goto a URL on the web?

### ISSUE THREAD

**Issue by Yahkal** [amzn/web-app-starter-kit-for-fire-tv#46]
I saw the dataURL in init.js and wanted to know if it can link to the web?

Does anyone know about this?

**Comment by maryga-amazon** [comment]
This parameter is the URL for feed that the app will use, and must link to a dataset or the app will error out. For information on the init.js and the data set, please see the document for the project type you are using (i.e. https://github.com/amzn/web-app-starter-kit-for-fire-tv/blob/master/docs/mrss-support.md)
