### ISSUE TITLE
How to create login and  subscription purchase inside webapp

### ISSUE THREAD

**Issue by agadev** [amzn/web-app-starter-kit-for-fire-tv#47]
I want to authenticate user first time they open app. If they don't have subscription on our servers , I want to customer to be able to purchase monthly or yearly subscription through amazon account.

**Comment by maryga-amazon** [comment]
You can use Amazon In-App Purchase which is supported for web apps. Please note that the IAP version in the template project is using V1 APIs, which are deprecated. If you are using IAP, please update the APIs to V2, as described in the developer docs: https://developer.amazon.com/docs/in-app-purchasing/iap-api-for-webapps-overview.html
