### ISSUE TITLE
Search on the Mrss script

### ISSUE THREAD

**Issue by xavierdante** [amzn/web-app-starter-kit-for-fire-tv#48]
I would like to know how to make the search button work on the MRS template or how to eliminate it from the Nav

**Comment by maryga-amazon** [comment]
To eliminate search you simply need to change the config option in the init.js called 'showSearch' from true to false.
If search is true, it will automatically enable searching of the MRSS data that is loaded into the app. The app will perform a string comparison of the search query against the title and description data in your dataset.

**Comment by xavierdante** [comment]
Thanks for your help.
I founded

Xavier
