### ISSUE TITLE
Question on OAuth

### ISSUE THREAD

**Issue by znap026** [amzn/web-app-starter-kit-for-fire-tv#5]
I was wondering if you knew if it would be possible to perform an OAuth 2.0 validation for a web app like this, and if so any pointers on where to learn about implementing it? Thanks

**Comment by russellbeattie** [comment]
Sorry for the delay - the Fire TV supports OAuth 2.0 validation for hosted web apps or via Cordova/PhoneGapp hybrid apps, so this could be added to the template pretty easily. I just tested the Login With Amazon service to double check and it worked fine: http://login.amazon.com/

**Comment by znap026** [comment]
Thanks for getting back, I was thinking of a hybrid app so it's good to know it's possible. I'll try and look at incorporating a phonegap app into a template, just got to get my head around the structure of that! Thanks again.

**Comment by craigcbrunner-amazon** [comment]
Marking this issue as closed. Thanks!
