### ISSUE TITLE
Youtube Channel starter pack 

### ISSUE THREAD

**Issue by adammaxon** [amzn/web-app-starter-kit-for-fire-tv#51]
Hello,
I am running into an insue when running the simple youtube starter pack. When running the code I get this error: 
model-youtube-api.js:59 Uncaught TypeError: Cannot read property 'snippet' of undefined
at YouTubeAPIModel. (model-youtube-api.js:59)
I have tried changing my user ID to Chanel ID and get the same error message. I tried to change model-youtube-api.js line 51 to:
url: "https://www.googleapis.com/youtube/v3/channels?part=snippet,id&id="+this.youtubeUser+"&key=" + this.devKey,
like glotv did and have had no luck.

**Comment by adammaxon** [comment]
fixed

**Comment by kbselander** [comment]
Could you Please enlighten how you fixed this issue?  I am currently running into this same bug.
