### ISSUE TITLE
D-Pad navigation doesn't work in any of the projects

### ISSUE THREAD

**Issue by shshekhar93** [amzn/web-app-starter-kit-for-fire-tv#63]
The keyboard navigation with D-Pad for all these projects seems to be broken in Silk as well as Firefox.

After the page is loaded (from my local server), the cursor hangs around and the d-pad controls the cursor rather than passing the key events to the page.

**Comment by russellbeattie-amazon** [comment]
Both Silk and Firefox seem to be capturing the remote's button presses for the virtual cursor. This is how they were designed - I did a quick look through Firefox's open source project (https://github.com/mozilla-mobile/firefox-tv) and there wasn't any obvious way to disable it. I would suggest submitting an issue with them, as it's outside the scope of this project.

Meanwhile, if you want to test your web app on Fire TV, please use the Amazon Web App Tester - it provides a relatively raw WebView wrapper (the same WebView that Firefox uses) and does not intercept key presses. You can find that here: https://www.amazon.com/Amazon-Digital-Services-Inc-Tester/dp/B00DZ3I1W8

Thanks!
